version: '1.0'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:7444
    volumes:
      - .:/usr/src/seminar-managemant/
    ports:
      - 7444:7444
    env_file:
      - ./.env.dev